name: deploy-client

on:
  push:
    branches:
      - master
    paths:
      - 'client/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd client && docker build -t ridhamezrigui/client .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{secretes.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secretes.DOCKER_PASSWORD}}
      - run: docker push ridhamezrigui/client
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{decretes.DIGITALOCEAN_ACCESS_TOKEN}}
      - run: dctl kubernetes cluster kubeconfig save ticketsApp
      - run: kubectl rollout restart deployment client-depl
