name: deploy-manifests 

on:
  push:
    branches:
      - master
    paths:
      - 'infra/**'

jobs:
  build:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
       - uses: digitalocean/action-doctl@v2
         with:
           token: ${{decretes.DIGITALOCEAN_ACCESS_TOKEN}}
       - run: dctl kubernetes cluster kubeconfig save ticketsApp
       - run : kubectl apply -f infra/k8s 
